language: node_js
node_js:
    - 10
script: yarn lint && yarn && yarn build
deploy:
    provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
        secure: $NPM_API_KEY
    on:
        tags: true
        repo: AckeeCZ/redux-utils